# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1c9d1f8b-1e69-4f54-b47c-089d1e2dbb47";
      fsType = "btrfs";
      options = [ "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1c9d1f8b-1e69-4f54-b47c-089d1e2dbb47";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1c9d1f8b-1e69-4f54-b47c-089d1e2dbb47";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/11F2-5D06";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/steam" =
    { device = "/dev/disk/by-uuid/80054438-f6c7-4863-ae35-2313cb084c43";
      fsType = "btrfs";
      options = [ "subvol=@steam" "compress=zstd" "ssd" "discard=async" "nofail" "x-systemd.device-timeout=5s" ];
    };

  fileSystems."/mnt/nas" =
    { device = "192.168.13.22:/mnt/nfspool/ProxmoxTrueNAS/nfsshare";
      fsType = "nfs";
      options = [ "nfsvers=4" "nofail" "x-systemd.automount" "x-systemd.idle-timeout=600" "x-systemd.mount-timeout=10s" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/86a029b1-7a15-4b46-b157-ac57075b3e02"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
